spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/boilerplate?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: boilerplate
    password: boilerplate
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: false
  redis:
    host: localhost
    port: 6379
  jwt:
    algorithm: HS256
    secret-key: boilerplate
    expire-second: 604800
    refresh-expire-second: 129600
  flyway:
    enabled: true
    baseline-on-migrate: false
    url: jdbc:mysql://localhost:5432/boilerplate
    user: boilerplate
    password: boilerplate
    locations: classpath:db/migration
logging:
  level:
    org.hibernate.SQL: debug